name: CI

on: [push]

jobs:
  build:

    runs-on: node-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install package.json
      run: npm install
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
